export type King = {
  edition: number
  name: string
  title: string
  description: string
  file: string
}

export const kings: King[] = [
  { edition: 1, name: "Sparkbane", title: "New King of the Forge", description: "The Diamond Hearted, Survivor of Bears", file: "Sparkbane.png" },
  { edition: 2, name: "Cybernaut", title: "King of the Cybervault", description: "Holder of the Diamond Fist, Lord of the Balanced Ledger", file: "Cybernaut.PNG" },
  { edition: 3, name: "Morgoth", title: "The Nightmare King", description: "The Sleepless Trader, The Warden of Wasted Wealth", file: "Morgoth.PNG" },
  { edition: 4, name: "Ser Hashalot", title: "King of the Unbroken Protocol", description: "Defender of Defi, Ruler of Ledgerlund", file: "Ser Hashalot.png" },
  { edition: 5, name: "Boneheart", title: "The Dead King", description: "Protector of the Aurum Path, The Walking Blade", file: "BoneHeart.png" },
  { edition: 6, name: "Merkleroot", title: "King of the Fractal Bloom", description: "Keeper of the Eternal Tree, Guardian of the First Branch", file: "Merkleroot.PNG" },
  { edition: 7, name: "Rusty", title: "The Gunslinger King", description: "Silk Road Bandit, Rider of the Rusted Ledger", file: "Rusty.PNG" },
  { edition: 8, name: "Bitgrim", title: "King of the Deep Mines", description: "Warden of the Block Below, Sovereign of the Underground Ledger", file: "Bitgrim.png" },
  { edition: 9, name: "Ironstrike", title: "Champion of the Iron Nodes", description: "Breaker of the Centralized Veins, The Immutable Monarch", file: "Ironstrike.png" },
  { edition: 10, name: "Hashirama", title: "King of the Shadow Clan", description: "Keeper of the Hidden Ledger, Bringer of Silent Wealth", file: "Hashirama.PNG" },
  { edition: 11, name: "Bucky", title: "King of the Free Block", description: "The Punk Sovereign, The Last Rebel", file: "Bucky.png" },
  { edition: 12, name: "Cipherion", title: "King of the Hidden Transaction", description: "Sage of the Silk Road, The Mempool Mage", file: "Cipherion.png" },
  { edition: 13, name: "Firebrand", title: "Leader of the Thermal Kingdom", description: "Keeper of the Immutable Flame, Collector of Reusable Energy", file: "Firebrand.png" },
  { edition: 14, name: "William", title: "The Butcher King", description: "The Butcher of Bitcoin, Master of the Chopping Block", file: "William.PNG" },
  { edition: 15, name: "Urseus", title: "King of the Blade", description: "The Northwind Sentinel, Protector of the Frozen Blocks", file: "Urseus.PNG" },
  { edition: 16, name: "Mortifex", title: "King of the Dark Markets", description: "Hráefn Cyning Þēowhandla, König des Schattenhandels", file: "Mortifex.PNG" },
  { edition: 17, name: "Nightblade", title: "Warrior of the Untamed Chain", description: "Protector of the Block, Phantom of the Prime Nodes", file: "Nightblade.PNG" },
  { edition: 18, name: "Veridant", title: "Lady of the Lake", description: "Protector of the Loch, Water Walker", file: "Veridant.PNG" },
  { edition: 19, name: "Galactix", title: "Intergalactic King of the Hooded Lings", description: "The Great Destroyer, The Epoch Lord", file: "Galactix.png" },
  { edition: 20, name: "Frostwave", title: "King of the Undying Chain", description: "Bringer of the Endless Winter, Herald of the Undying Flow", file: "Frostwave.png" },
  { edition: 21, name: "1001001", title: "The Merkle Monarch", description: "The Algorithmic Lord, Keeper of the Cryptic Path", file: "1001001.png" },
  { edition: 22, name: "John", title: "The Surviving King", description: "The OG, The Unbearish", file: "John.png" },
  { edition: 23, name: "Brakkoth", title: "King of the Broken Blade", description: "Ash Walker, Destroyer of Code", file: "Brakkoth.PNG" },
  { edition: 24, name: "Bitzerker", title: "The King of the Endless Grind", description: "The Dark Node, The Block Swordsman", file: "Bitzerker.png" },
  { edition: 25, name: "Gigablock", title: "King of the Giga Realm", description: "The Chainlord Supreme, King Swooty", file: "Gigablock.png" },
  { edition: 26, name: "Balrog", title: "King of the Decentralized Plains", description: "The Bulldozer, The Fat Stack", file: "Balrog.PNG" },
  { edition: 27, name: "Vorr'Zhul", title: "The Nether King", description: "The Dark Web, Zyphoroth the Destroyer", file: "VORR_ZHUL.PNG" },
  { edition: 28, name: "Zeno X", title: "The King Quant", description: "Lord of the Quantum Mine, Whisperer of the AI Agents", file: "Zeno X.PNG" },
  { edition: 29, name: "Commander Vex", title: "King of the Space Fleet", description: "Warden of the Orbital Chains, Master of the Zero-Gravity Markets", file: "Commander Vex.PNG" },
  { edition: 30, name: "Dr. Satoshi", title: "The King of the Endless Bock", description: "The Architect of Immutable Reality, The Quantum Watcher", file: "Dr. Satoshi.PNG" },
  { edition: 31, name: "Hashikaze", title: "The King of the Swift Fist", description: "The Decentralized Warrior, Wielder of the Iron Palm", file: "Hashikaze.PNG" },
  { edition: 32, name: "Ursaroth", title: "The Beast King", description: "The Shadowpaw Tyrant, The Unshackled Mauler", file: "Ursaroth.PNG" },
  { edition: 33, name: "Hashiro", title: "The Duel King", description: "Shadō no Kenshi, The Unbreakable Sword", file: "Hashiro.PNG" },
  { edition: 34, name: "Ulfric", title: "The Wolf King", description: "The Undying Fang, Keeper of the Frozen Ledger", file: "Ulfric.PNG" },
  { edition: 35, name: "Satori Prime", title: "The King of Enlightenment", description: "The Harmonious One, Bound by Neither Code nor Chaos", file: "Satori Prime.PNG" },
  { edition: 36, name: "Oryxx", title: "The Flayed King", description: "The 4th Bone Lord, The Skinless Sovereign", file: "Oryxx.PNG" },
  { edition: 37, name: "Oni-goru", title: "Demon King of the Reef", description: "Oceanic Hashling King, Oni Guardian", file: "Oni-Goru.PNG" },
  { edition: 38, name: "Chromagus", title: "the Chrome Throne", description: "King of the Forged Gaze, Mirror to the Chain", file: "Chromagus.PNG" },
  { edition: 39, name: "San Peperinus", title: "The Pepe Saint", description: "The Blessed Amphibian, Saint of the Sacred Meme", file: "San Peperinus.PNG" },
  { edition: 40, name: "Orrilo", title: "The Code King", description: "The Wizard", file: "Orrilo.PNG" },
  { edition: 41, name: "Grull", title: "High Warlord of Hashmark", description: "The Reluctant King, Hashmark's Saviour", file: "Grull.PNG" },
  { edition: 42, name: "Alboran", title: "The Winter Warlord", description: "Titan of the Wildlands, The Gentle Storm", file: "Alboran.PNG" },
  { edition: 43, name: "Sir Billiam", title: "The Billy King", description: "The Billion Dollar Leige, The Knight of the Round Bubble", file: "Sir Billiam.PNG" },
  { edition: 44, name: "Roggath", title: "The Beast King", description: "The Beast Master, Lord of the Wilds", file: "Roggath.PNG" },
  { edition: 45, name: "Nocturus", title: "The Horned Hollow", description: "The WaterStag, The Umbral Knight", file: "Nocturus.PNG" },
  { edition: 46, name: "Krannok", title: "The Black Line", description: "The Giant Shadow, The Dark Mist", file: "Krannok.PNG" },
  { edition: 47, name: "The Don", title: "The Self-Appointed King of Bitcoin", description: "The Breaker of Censorship, The Pumper of Bags", file: "The Don.PNG" },
  { edition: 48, name: "Blazwick", title: "The Toxic Fang", description: "The Rusty Reaper, Battle Regent Prime", file: "Blazwick.PNG" },
  { edition: 49, name: "NUBULO", title: "Soveriegn of the Softverse", description: "The Cloud Lord, The Velvet OS", file: "Nubulo.PNG" },
  { edition: 50, name: "Griddor", title: "King of the Block Realms", description: "The Square Lord, The BLOCK", file: "Griddor.PNG" },
  { edition: 51, name: "Draxis", title: "The King of Pipelines", description: "The Lubester, the synergist", file: "Draxis.PNG" },
  { edition: 52, name: "Nibblord", title: "The King of Blumplund", description: "Grumbles, Grimbus", file: "Nibblord.PNG" },
  { edition: 53, name: "Pichasho", title: "The King of Cubelund", description: "The Blue King, Cubist Commander", file: "Pichasho.PNG" },
  { edition: 54, name: "Hashquiat", title: "The King of Bootlegs", description: "The Street Lord, The Iterator", file: "Hashquiat.PNG" },
  { edition: 55, name: "HoneyPaw", title: "The Gentle Crown", description: "Baron of Bullish Bears, The Pink Skink", file: "HoneyPaw.PNG" },
  { edition: 56, name: "Bogmaw", title: "The Swamp King", description: "The Boar of Bulls, The Bayou Beast", file: "Bogmaw.PNG" },
  { edition: 57, name: "Corruptor Rex", title: "The Glitch Lord", description: "The Worm, The Trojan", file: "Corruptor Rex.PNG" },
  { edition: 58, name: "Hashula", title: "The Vampyre King", description: "The Vieled Truth, The Dragon", file: "Hashula.png" },
  { edition: 59, name: "Craydon", title: "The Scribble Crown", description: "Doodle King, Sketch Lord", file: "Craydon.PNG" },
  { edition: 60, name: "Caspion", title: "The Bat King", description: "The Echo Keeper, The Bone Collecter", file: "Caspion.PNG" },
  { edition: 61, name: "Phaseling", title: "The Quantum King", description: "Light Catcher, Wave Lord", file: "Phaseling.PNG" },
  { edition: 62, name: "Hashiah", title: "The Monk King", description: "Warrior Monk, Keeper of the Orange", file: "Hashiah.PNG" },
  { edition: 63, name: "Buddash", title: "The Enlightened", description: "The Free, The Delightened", file: "Buddash.PNG" },
  { edition: 64, name: "Praxis Thorn", title: "The Anarchist", description: "Steward of the Unruled, Herald of the Black Banner", file: "Praxis Thorn.PNG" },
  { edition: 65, name: "Bendigo", title: "The Rubber Forest King", description: "Bounceroy, King Rubberwick", file: "Bendigo.PNG" },
  { edition: 66, name: "Prismark", title: "The Owl", description: "King of the Tesselates, the Geometric Genius", file: "Prismark.PNG" },
  { edition: 67, name: "Carl", title: "The King", description: "Baron of Bedtime Stories, Lord of the Lunchbox League", file: "Carl.PNG" },
  { edition: 68, name: "Grundle", title: "King of the Hidden Valley", description: "The Peace Keeper, Sanctuary Saviour", file: "Grundle.PNG" },
  { edition: 69, name: "Pepedemus", title: "King of the Meme Martyrs", description: "Martyr of the Meme Basilica, Saint of the Bog", file: "Pepedemus.png" },
  { edition: 70, name: "Sparkhelm", title: "King of the Embers", description: "Lord of Flint and Horn, Warden of the Strikefire", file: "Sparkhelm.png" },
  { edition: 71, name: "Plushius Rex", title: "The Celestial", description: "Warden of the Lullaby Sky, Keeper of the Meteor Mittens", file: "Plushius Rex.png" },
  { edition: 72, name: "Lord Whiskers", title: "The Water Bender", description: "Regent of the Velvet Steps, Keeper of Moonlit Fishbones", file: "Lord Whiskers.png" },
  { edition: 73, name: "Inkwhittle", title: "The Doodle King", description: "Monarch of the Margin, Warden of the Wobble Line", file: "Inkwhittle.png" },
  { edition: 74, name: "Ember Maw", title: "The Pack King", description: "Marshal of the Night Hunt", file: "Ember Maw.png" },
  { edition: 75, name: "MoonBlink", title: "The Curious King", description: "Keeper of the Witch's Window", file: "Moonblink.png" },
  { edition: 76, name: "Inverso", title: "The Reverse King", description: "Lord of the Flipworld", file: "Inverso.png" },
  { edition: 77, name: "Glimmergloom", title: "The Light in the Darkness", description: "Custodian of the Comfortable Dark", file: "Glimmergloom.png" },
  { edition: 78, name: "Sir Scribbleton", title: "The King of Imagination", description: "Warden of the Dust-Crowned Desk", file: "Sir Scribbleton.png" },
  { edition: 79, name: "Volt", title: "The Arc Regent", description: "Crown of the Storm-Arc", file: "Volt.PNG" },
  { edition: 80, name: "Lumenaire", title: "The Lightbringer", description: "Keeper of the Halo Blade", file: "Lumenaire.PNG" },
  { edition: 81, name: "Joyvoid", title: "King of the Arcade Abyss", description: "Steward of the Neon Rift", file: "Joyvoid.PNG" },
  { edition: 82, name: "Tally", title: "Keeper of the Thread-Field", description: "Warden of the Knotted Field", file: "Tally.PNG" },
  { edition: 83, name: "Hexarch Morrow", title: "Lord of the Hiveways", description: "Chancellor of the Chitin Crown", file: "Hexarch Morrow.PNG" },
  { edition: 84, name: "Auxillian", title: "Keeper of the Signal", description: "Keeper of the Aux Crown", file: "Auxillian.PNG" },
  { edition: 85, name: "Laughtrack", title: "the Haunted Brand", description: "Creator of the Smile-Engine", file: "Laughtrack.PNG" },
  { edition: 86, name: "Whimsy", title: "Empress of the Cute Curse", description: "The Laughing Monarch", file: "Whimsy.PNG" },
  { edition: 87, name: "Alabastriel", title: "The Bright Dominion", description: "The Quiet Queen", file: "Alabastriel.PNG" },
  { edition: 88, name: "Starhome", title: "The King of the ET's", description: "Keeper of the Returning Path", file: "Starhome.PNG" },
  { edition: 89, name: "Bitdick", title: "The King of BTC Art", description: "The Keeper of Irony", file: "Bitdick.PNG" },
  { edition: 90, name: "Mnemora", title: "The Keeper of the Old Ways", description: "The First Queen", file: "Mnemora.PNG" },
  { edition: 91, name: "Sonara", title: "Queen of the Inner Peace", description: "The Peaceful Arbitrator", file: "Sonara.PNG" },
  { edition: 92, name: "King Dog", title: "The DOG King", description: "The Meme Monarch", file: "DOGling.PNG" },
  { edition: 93, name: "CelKing", title: "The King of the Keys", description: "The Key Keeper", file: "Celking.PNG" },
  { edition: 94, name: "Onyxia", title: "The Black Queen", description: "The Keeper of Krannok", file: "Onyxia.PNG" },
  { edition: 95, name: "Spamling", title: "The King of Ord", description: "The Great Extractor", file: "Spamling.PNG" },
  { edition: 96, name: "Hydress", title: "The Market Demonia", description: "Queen of the Pick", file: "Hydress.PNG" },
  { edition: 97, name: "Mad Molly", title: "The Pink Pirate", description: "The Bitcoin Buccaneer", file: "Mad Molly.PNG" },
  { edition: 98, name: "King Zorga", title: "The King of the Hashlien's", description: "Hashlien Prime", file: "King Zorga.PNG" },
  { edition: 99, name: "Sheepling", title: "The Wooly King", description: "The Herd Worker, Lord of the Lambs", file: "Sheepling.PNG" },
  { edition: 100, name: "Apeling", title: "King of the Bull Market", description: "The Stereotype, The Holder of Diamonds", file: "Apeling.PNG" },
]
