export type King = {
  edition: number
  name: string
  title: string
  description: string
  file: string
}

export const kings: King[] = [
  { edition: 1, name: "Sparkbane", title: "New King of the Forge", description: "The Diamond Hearted, Survivor of Bears", file: "sparkbane.webp" },
  { edition: 2, name: "Cybernaut", title: "King of the Cybervault", description: "Holder of the Diamond Fist, Lord of the Balanced Ledger", file: "cybernaut.webp" },
  { edition: 3, name: "Morgoth", title: "The Nightmare King", description: "The Sleepless Trader, The Warden of Wasted Wealth", file: "morgoth.webp" },
  { edition: 4, name: "Ser Hashalot", title: "King of the Unbroken Protocol", description: "Defender of Defi, Ruler of Ledgerlund", file: "ser-hashalot.webp" },
  { edition: 5, name: "Boneheart", title: "The Dead King", description: "Protector of the Aurum Path, The Walking Blade", file: "boneheart.webp" },
  { edition: 6, name: "Merkleroot", title: "King of the Fractal Bloom", description: "Keeper of the Eternal Tree, Guardian of the First Branch", file: "merkleroot.webp" },
  { edition: 7, name: "Rusty", title: "The Gunslinger King", description: "Silk Road Bandit, Rider of the Rusted Ledger", file: "rusty.webp" },
  { edition: 8, name: "Bitgrim", title: "King of the Deep Mines", description: "Warden of the Block Below, Sovereign of the Underground Ledger", file: "bitgrim.webp" },
  { edition: 9, name: "Ironstrike", title: "Champion of the Iron Nodes", description: "Breaker of the Centralized Veins, The Immutable Monarch", file: "ironstrike.webp" },
  { edition: 10, name: "Hashirama", title: "King of the Shadow Clan", description: "Keeper of the Hidden Ledger, Bringer of Silent Wealth", file: "hashirama.webp" },
  { edition: 11, name: "Bucky", title: "King of the Free Block", description: "The Punk Sovereign, The Last Rebel", file: "bucky.webp" },
  { edition: 12, name: "Cipherion", title: "King of the Hidden Transaction", description: "Sage of the Silk Road, The Mempool Mage", file: "cipherion.webp" },
  { edition: 13, name: "Firebrand", title: "Leader of the Thermal Kingdom", description: "Keeper of the Immutable Flame, Collector of Reusable Energy", file: "firebrand.webp" },
  { edition: 14, name: "William", title: "The Butcher King", description: "The Butcher of Bitcoin, Master of the Chopping Block", file: "william.webp" },
  { edition: 15, name: "Urseus", title: "King of the Blade", description: "The Northwind Sentinel, Protector of the Frozen Blocks", file: "urseus.webp" },
  { edition: 16, name: "Mortifex", title: "King of the Dark Markets", description: "Hráefn Cyning Þēowhandla, König des Schattenhandels", file: "mortifex.webp" },
  { edition: 17, name: "Nightblade", title: "Warrior of the Untamed Chain", description: "Protector of the Block, Phantom of the Prime Nodes", file: "nightblade.webp" },
  { edition: 18, name: "Veridant", title: "Lady of the Lake", description: "Protector of the Loch, Water Walker", file: "veridant.webp" },
  { edition: 19, name: "Galactix", title: "Intergalactic King of the Hooded Lings", description: "The Great Destroyer, The Epoch Lord", file: "galactix.webp" },
  { edition: 20, name: "Frostwave", title: "King of the Undying Chain", description: "Bringer of the Endless Winter, Herald of the Undying Flow", file: "frostwave.webp" },
  { edition: 21, name: "1001001", title: "The Merkle Monarch", description: "The Algorithmic Lord, Keeper of the Cryptic Path", file: "1001001.webp" },
  { edition: 22, name: "John", title: "The Surviving King", description: "The OG, The Unbearish", file: "john.webp" },
  { edition: 23, name: "Brakkoth", title: "King of the Broken Blade", description: "Ash Walker, Destroyer of Code", file: "brakkoth.webp" },
  { edition: 24, name: "Bitzerker", title: "The King of the Endless Grind", description: "The Dark Node, The Block Swordsman", file: "bitzerker.webp" },
  { edition: 25, name: "Gigablock", title: "King of the Giga Realm", description: "The Chainlord Supreme, King Swooty", file: "gigablock.webp" },
  { edition: 26, name: "Balrog", title: "King of the Decentralized Plains", description: "The Bulldozer, The Fat Stack", file: "balrog.webp" },
  { edition: 27, name: "Vorr'Zhul", title: "The Nether King", description: "The Dark Web, Zyphoroth the Destroyer", file: "vorr_zhul.webp" },
  { edition: 28, name: "Zeno X", title: "The King Quant", description: "Lord of the Quantum Mine, Whisperer of the AI Agents", file: "zeno-x.webp" },
  { edition: 29, name: "Commander Vex", title: "King of the Space Fleet", description: "Warden of the Orbital Chains, Master of the Zero-Gravity Markets", file: "commander-vex.webp" },
  { edition: 30, name: "Dr. Satoshi", title: "The King of the Endless Bock", description: "The Architect of Immutable Reality, The Quantum Watcher", file: "dr.-satoshi.webp" },
  { edition: 31, name: "Hashikaze", title: "The King of the Swift Fist", description: "The Decentralized Warrior, Wielder of the Iron Palm", file: "hashikaze.webp" },
  { edition: 32, name: "Ursaroth", title: "The Beast King", description: "The Shadowpaw Tyrant, The Unshackled Mauler", file: "ursaroth.webp" },
  { edition: 33, name: "Hashiro", title: "The Duel King", description: "Shadō no Kenshi, The Unbreakable Sword", file: "hashiro.webp" },
  { edition: 34, name: "Ulfric", title: "The Wolf King", description: "The Undying Fang, Keeper of the Frozen Ledger", file: "ulfric.webp" },
  { edition: 35, name: "Satori Prime", title: "The King of Enlightenment", description: "The Harmonious One, Bound by Neither Code nor Chaos", file: "satori-prime.webp" },
  { edition: 36, name: "Oryxx", title: "The Flayed King", description: "The 4th Bone Lord, The Skinless Sovereign", file: "oryxx.webp" },
  { edition: 37, name: "Oni-goru", title: "Demon King of the Reef", description: "Oceanic Hashling King, Oni Guardian", file: "oni-goru.webp" },
  { edition: 38, name: "Chromagus", title: "the Chrome Throne", description: "King of the Forged Gaze, Mirror to the Chain", file: "chromagus.webp" },
  { edition: 39, name: "San Peperinus", title: "The Pepe Saint", description: "The Blessed Amphibian, Saint of the Sacred Meme", file: "san-peperinus.webp" },
  { edition: 40, name: "Orrilo", title: "The Code King", description: "The Wizard", file: "orrilo.webp" },
  { edition: 41, name: "Grull", title: "High Warlord of Hashmark", description: "The Reluctant King, Hashmark's Saviour", file: "grull.webp" },
  { edition: 42, name: "Alboran", title: "The Winter Warlord", description: "Titan of the Wildlands, The Gentle Storm", file: "alboran.webp" },
  { edition: 43, name: "Sir Billiam", title: "The Billy King", description: "The Billion Dollar Leige, The Knight of the Round Bubble", file: "sir-billiam.webp" },
  { edition: 44, name: "Roggath", title: "The Beast King", description: "The Beast Master, Lord of the Wilds", file: "roggath.webp" },
  { edition: 45, name: "Nocturus", title: "The Horned Hollow", description: "The WaterStag, The Umbral Knight", file: "nocturus.webp" },
  { edition: 46, name: "Krannok", title: "The Black Line", description: "The Giant Shadow, The Dark Mist", file: "krannok.webp" },
  { edition: 47, name: "The Don", title: "The Self-Appointed King of Bitcoin", description: "The Breaker of Censorship, The Pumper of Bags", file: "the-don.webp" },
  { edition: 48, name: "Blazwick", title: "The Toxic Fang", description: "The Rusty Reaper, Battle Regent Prime", file: "blazwick.webp" },
  { edition: 49, name: "NUBULO", title: "Soveriegn of the Softverse", description: "The Cloud Lord, The Velvet OS", file: "nubulo.webp" },
  { edition: 50, name: "Griddor", title: "King of the Block Realms", description: "The Square Lord, The BLOCK", file: "griddor.webp" },
  { edition: 51, name: "Draxis", title: "The King of Pipelines", description: "The Lubester, the synergist", file: "draxis.webp" },
  { edition: 52, name: "Nibblord", title: "The King of Blumplund", description: "Grumbles, Grimbus", file: "nibblord.webp" },
  { edition: 53, name: "Pichasho", title: "The King of Cubelund", description: "The Blue King, Cubist Commander", file: "pichasho.webp" },
  { edition: 54, name: "Hashquiat", title: "The King of Bootlegs", description: "The Street Lord, The Iterator", file: "hashquiat.webp" },
  { edition: 55, name: "HoneyPaw", title: "The Gentle Crown", description: "Baron of Bullish Bears, The Pink Skink", file: "honeypaw.webp" },
  { edition: 56, name: "Bogmaw", title: "The Swamp King", description: "The Boar of Bulls, The Bayou Beast", file: "bogmaw.webp" },
  { edition: 57, name: "Corruptor Rex", title: "The Glitch Lord", description: "The Worm, The Trojan", file: "corruptor-rex.webp" },
  { edition: 58, name: "Hashula", title: "The Vampyre King", description: "The Vieled Truth, The Dragon", file: "hashula.webp" },
  { edition: 59, name: "Craydon", title: "The Scribble Crown", description: "Doodle King, Sketch Lord", file: "craydon.webp" },
  { edition: 60, name: "Caspion", title: "The Bat King", description: "The Echo Keeper, The Bone Collecter", file: "caspion.webp" },
  { edition: 61, name: "Phaseling", title: "The Quantum King", description: "Light Catcher, Wave Lord", file: "phaseling.webp" },
  { edition: 62, name: "Hashiah", title: "The Monk King", description: "Warrior Monk, Keeper of the Orange", file: "hashiah.webp" },
  { edition: 63, name: "Buddash", title: "The Enlightened", description: "The Free, The Delightened", file: "buddash.webp" },
  { edition: 64, name: "Praxis Thorn", title: "The Anarchist", description: "Steward of the Unruled, Herald of the Black Banner", file: "praxis-thorn.webp" },
  { edition: 65, name: "Bendigo", title: "The Rubber Forest King", description: "Bounceroy, King Rubberwick", file: "bendigo.webp" },
  { edition: 66, name: "Prismark", title: "The Owl", description: "King of the Tesselates, the Geometric Genius", file: "prismark.webp" },
  { edition: 67, name: "Carl", title: "The King", description: "Baron of Bedtime Stories, Lord of the Lunchbox League", file: "carl.webp" },
  { edition: 68, name: "Grundle", title: "King of the Hidden Valley", description: "The Peace Keeper, Sanctuary Saviour", file: "grundle.webp" },
  { edition: 69, name: "Pepedemus", title: "King of the Meme Martyrs", description: "Martyr of the Meme Basilica, Saint of the Bog", file: "pepedemus.webp" },
  { edition: 70, name: "Sparkhelm", title: "King of the Embers", description: "Lord of Flint and Horn, Warden of the Strikefire", file: "sparkhelm.webp" },
  { edition: 71, name: "Plushius Rex", title: "The Celestial", description: "Warden of the Lullaby Sky, Keeper of the Meteor Mittens", file: "plushius-rex.webp" },
  { edition: 72, name: "Lord Whiskers", title: "The Water Bender", description: "Regent of the Velvet Steps, Keeper of Moonlit Fishbones", file: "lord-whiskers.webp" },
  { edition: 73, name: "Inkwhittle", title: "The Doodle King", description: "Monarch of the Margin, Warden of the Wobble Line", file: "inkwhittle.webp" },
  { edition: 74, name: "Ember Maw", title: "The Pack King", description: "Marshal of the Night Hunt", file: "ember-maw.webp" },
  { edition: 75, name: "MoonBlink", title: "The Curious King", description: "Keeper of the Witch's Window", file: "moonblink.webp" },
  { edition: 76, name: "Inverso", title: "The Reverse King", description: "Lord of the Flipworld", file: "inverso.webp" },
  { edition: 77, name: "Glimmergloom", title: "The Light in the Darkness", description: "Custodian of the Comfortable Dark", file: "glimmergloom.webp" },
  { edition: 78, name: "Sir Scribbleton", title: "The King of Imagination", description: "Warden of the Dust-Crowned Desk", file: "sir-scribbleton.webp" },
  { edition: 79, name: "Volt", title: "The Arc Regent", description: "Crown of the Storm-Arc", file: "volt.webp" },
  { edition: 80, name: "Lumenaire", title: "The Lightbringer", description: "Keeper of the Halo Blade", file: "lumenaire.webp" },
  { edition: 81, name: "Joyvoid", title: "King of the Arcade Abyss", description: "Steward of the Neon Rift", file: "joyvoid.webp" },
  { edition: 82, name: "Tally", title: "Keeper of the Thread-Field", description: "Warden of the Knotted Field", file: "tally.webp" },
  { edition: 83, name: "Hexarch Morrow", title: "Lord of the Hiveways", description: "Chancellor of the Chitin Crown", file: "hexarch-morrow.webp" },
  { edition: 84, name: "Auxillian", title: "Keeper of the Signal", description: "Keeper of the Aux Crown", file: "auxillian.webp" },
  { edition: 85, name: "Laughtrack", title: "the Haunted Brand", description: "Creator of the Smile-Engine", file: "laughtrack.webp" },
  { edition: 86, name: "Whimsy", title: "Empress of the Cute Curse", description: "The Laughing Monarch", file: "whimsy.webp" },
  { edition: 87, name: "Alabastriel", title: "The Bright Dominion", description: "The Quiet Queen", file: "alabastriel.webp" },
  { edition: 88, name: "Starhome", title: "The King of the ET's", description: "Keeper of the Returning Path", file: "starhome.webp" },
  { edition: 89, name: "Bitdick", title: "The King of BTC Art", description: "The Keeper of Irony", file: "bitdick.webp" },
  { edition: 90, name: "Mnemora", title: "The Keeper of the Old Ways", description: "The First Queen", file: "mnemora.webp" },
  { edition: 91, name: "Sonara", title: "Queen of the Inner Peace", description: "The Peaceful Arbitrator", file: "sonara.webp" },
  { edition: 92, name: "King Dog", title: "The DOG King", description: "The Meme Monarch", file: "dogling.webp" },
  { edition: 93, name: "CelKing", title: "The King of the Keys", description: "The Key Keeper", file: "celking.webp" },
  { edition: 94, name: "Onyxia", title: "The Black Queen", description: "The Keeper of Krannok", file: "onyxia.webp" },
  { edition: 95, name: "Spamling", title: "The King of Ord", description: "The Great Extractor", file: "spamling.webp" },
  { edition: 96, name: "Hydress", title: "The Market Demonia", description: "Queen of the Pick", file: "hydress.webp" },
  { edition: 97, name: "Mad Molly", title: "The Pink Pirate", description: "The Bitcoin Buccaneer", file: "mad-molly.webp" },
  { edition: 98, name: "King Zorga", title: "The King of the Hashlien's", description: "Hashlien Prime", file: "king-zorga.webp" },
  { edition: 99, name: "Sheepling", title: "The Wooly King", description: "The Herd Worker, Lord of the Lambs", file: "sheepling.webp" },
  { edition: 100, name: "Apeling", title: "King of the Bull Market", description: "The Stereotype, The Holder of Diamonds", file: "apeling.webp" },
]
