export type PortfolioImage = {
  file: string
  title?: string
}

export const images: PortfolioImage[] = [
  { file: "amsterdam.png", title: "Amsterdam" },
  { file: "chisel-peak.jpeg", title: "Chisel Peak" },
  { file: "eagle-coloured.png", title: "Eagle" },
  { file: "fall.png", title: "Fall" },
  { file: "frame-3.png", title: "Frame 3" },
  { file: "gaucho.png", title: "Gaucho" },
  { file: "king-graff.png", title: "King Graff" },
  { file: "nyc.png", title: "NYC" },
  { file: "night-market-stand.png", title: "Night Market Stand" },
  { file: "night-market.png", title: "Night Market" },
  { file: "renegade.png", title: "Renegade" },
  { file: "sourboy.png", title: "Sourboy" },
  { file: "soyer-and-daughter.png", title: "Soyer and Daughter" },
  { file: "twins.png", title: "Twins" },
  { file: "mfyc.png", title: "MFYC" },
  { file: "money-land.png", title: "Money Land" },
  { file: "mycellium-tech-render.png", title: "Mycelium Tech" },
  { file: "new-year-grandma.png", title: "New Year Grandma" },
  { file: "plane-sketch.png", title: "Plane Sketch" },
  { file: "self-portrait.png", title: "Self Portrait" },
  { file: "spooky-bois.png", title: "Spooky Bois" },
  { file: "spring.png", title: "Spring" },
  { file: "the-aquarium.png", title: "The Aquarium" },
  { file: "third-eye-ipa.png", title: "Third Eye IPA" },
  { file: "veritai-hq.png", title: "Veritai HQ" },
  { file: "wedding.png", title: "Wedding" },
  { file: "yule.png", title: "Yule" },
  { file: "brain-pattern.png", title: "Brain Pattern" },
  { file: "tech-barn.png", title: "Tech Barn" },
  { file: "astroboy-sunglasses-1.png", title: "Astro Boy Glasses" },
  { file: "tyson-sunglasses-1.png", title: "Tyson Glasses" },
  { file: "goblin-and-cat.png", title: "Goblin and Cat" },
  { file: "snowy-craque.png", title: "Snowy Craque" },
  { file: "big-cat.jpeg", title: "Big Cat" },
  { file: "big-sword.png", title: "Big Sword" },
  { file: "chicago.png", title: "Chicago" },
  { file: "eagle.png", title: "Eagle" },
  { file: "ice-wolf.png", title: "Ice Wolf" },
  { file: "lords-shield.png", title: "Lords Shield" },
  { file: "supreme-savage.png", title: "Supreme Savage" },
  { file: "gaucho-digital.png", title: "Gaucho Digital" },
  { file: "imagination-fish.png", title: "Imagination Fish" },
  { file: "moon-cat.png", title: "Moon Cat" },
  { file: "submerge.png", title: "Submerge" },
  { file: "the-lighthouse.png", title: "The Lighthouse" },
  { file: "the-skyscraper.png", title: "The Skyscraper" },
  { file: "the-valley.png", title: "The Valley" },
  { file: "turtle-town.png", title: "Turtle Town" },
  { file: "boston-on-the-bed.png", title: "Boston on the Bed" },
  { file: "whiskey-glass-study.png", title: "Whiskey Glass Study" },
]
