export type PortfolioImage = {
  file: string
  title?: string
}

export const images: PortfolioImage[] = [
  { file: "amsterdam.webp", title: "Amsterdam" },
  { file: "chisel-peak.webp", title: "Chisel Peak" },
  { file: "eagle-coloured.webp", title: "Eagle" },
  { file: "fall.webp", title: "Fall" },
  { file: "frame-3.webp", title: "Frame 3" },
  { file: "gaucho.webp", title: "Gaucho" },
  { file: "king-graff.webp", title: "King Graff" },
  { file: "nyc.webp", title: "NYC" },
  { file: "night-market-stand.webp", title: "Night Market Stand" },
  { file: "night-market.webp", title: "Night Market" },
  { file: "renegade.webp", title: "Renegade" },
  { file: "sourboy.webp", title: "Sourboy" },
  { file: "soyer-and-daughter.webp", title: "Soyer and Daughter" },
  { file: "twins.webp", title: "Twins" },
  { file: "mfyc.webp", title: "MFYC" },
  { file: "money-land.webp", title: "Money Land" },
  { file: "mycellium-tech-render.webp", title: "Mycelium Tech" },
  { file: "new-year-grandma.webp", title: "New Year Grandma" },
  { file: "plane-sketch.webp", title: "Plane Sketch" },
  { file: "self-portrait.webp", title: "Self Portrait" },
  { file: "spooky-bois.webp", title: "Spooky Bois" },
  { file: "spring.webp", title: "Spring" },
  { file: "the-aquarium.webp", title: "The Aquarium" },
  { file: "third-eye-ipa.webp", title: "Third Eye IPA" },
  { file: "veritai-hq.webp", title: "Veritai HQ" },
  { file: "wedding.webp", title: "Wedding" },
  { file: "yule.webp", title: "Yule" },
  { file: "brain-pattern.webp", title: "Brain Pattern" },
  { file: "tech-barn.webp", title: "Tech Barn" },
  { file: "astroboy-sunglasses-1.webp", title: "Astro Boy Glasses" },
  { file: "tyson-sunglasses-1.webp", title: "Tyson Glasses" },
  { file: "goblin-and-cat.webp", title: "Goblin and Cat" },
  { file: "snowy-craque.webp", title: "Snowy Craque" },
  { file: "big-cat.webp", title: "Big Cat" },
  { file: "big-sword.webp", title: "Big Sword" },
  { file: "chicago.webp", title: "Chicago" },
  { file: "eagle.webp", title: "Eagle" },
  { file: "ice-wolf.webp", title: "Ice Wolf" },
  { file: "lords-shield.webp", title: "Lords Shield" },
  { file: "supreme-savage.webp", title: "Supreme Savage" },
  { file: "imagination-fish.webp", title: "Imagination Fish" },
  { file: "moon-cat.webp", title: "Moon Cat" },
  { file: "submerge.webp", title: "Submerge" },
  { file: "the-lighthouse.webp", title: "The Lighthouse" },
  { file: "the-skyscraper.webp", title: "The Skyscraper" },
  { file: "the-valley.webp", title: "The Valley" },
  { file: "turtle-town.webp", title: "Turtle Town" },
  { file: "boston-on-the-bed.webp", title: "Boston on the Bed" },
  { file: "whiskey-glass-study.webp", title: "Whiskey Glass Study" },
]
